sfmrabbit:
    image: rabbitmq@sha256:a5180a37b0baebb938ee9d12dd11eed64a909288d7f344e24771278f8a122367
    #image: rabbitmq:3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmuidb:
    image: gwul/sfm-ui-db:master
    environment:
        - POSTGRES_PASSWORD=gherD42#dl5
    restart: always
sfmuiapp:
    image: gwul/sfm-ui:master
    ports:
        - "8080:80"
    links:
        - sfmuidb:db
        - sfmrabbit:mq
    environment:
        - SFM_DEBUG=True
        - SFM_SITE_ADMIN_EMAIL=nowhere@example.com
    restart: always
    volumes:
        - /sfm-data
sfmtwitterrestharvester:
    image: gwul/sfm-twitter-rest-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    volumes_from:
        - sfmuiapp:rw
    environment:
        - DEBUG=False
sfmweiboharvester:
    image: gwul/sfm-weibo-harvester:master
    links:
        - sfmrabbit:mq
    restart: always
    volumes_from:
        - sfmuiapp:rw
    environment:
        - DEBUG=False
sfmelk:
  build: dev
  ports:
    #Kibana web interface
    - "5601:5601"
    #Elasticsearch JSON interface
    - "9200:9200"
    #Logstash server
    - "5000:5000"
  volumes:
    - "..:/opt/sfm-elk"
  links:
    - sfmrabbit:mq
  volumes_from:
    - sfmuiapp:ro
  environment:
    - DEBUG=True
  #You can get the collection id from the collection detail page in SFM UI.
  #command: --collection=04afb3d938aa468ca2a71de0824da126xxxxxx
